global_workspace:
    latent_dim: 12  

    loss_coefficients:
        cycles: 1
        contrastives: 0.1
        demi_cycles: 1
        translations: 1
    encoders:
        hidden_dim: 256
        n_layers: 2

    decoders:
        hidden_dim: 256
        n_layers: 2

seed: 1

training:
    optim:
        lr: 1e-5
        weight_decay: 1e-6
        max_lr: 1.5e-4
        start_lr: 1e-4
        end_lr: 1e-5
        pct_start: 0.03

    max_steps: 300000
    devices: 1


logging:
    log_val_medias_every_n_epochs: 1
    log_train_medias_every_n_epochs: 1
    filter_images:
        - pred_trans_attr_to_attr
        - pred_trans_v_latents_to_v_latents
        - pred_trans_attr_to_v_latents
        - pred_trans_v_latents_to_attr
        - pred_cycle_v_latents_to_attr
        - pred_cycle_attr_to_v_latents
        - pred_cycle_v_latents_to_v_latents
        - pred_cycle_attr_to_attr



# domains:
#     - checkpoint_path: "#{default_root_dir}/checkpoints/domain_attr.ckpt"
#       domain_type: attr_legacy_no_color
#       args:
#           n_unpaired: "#{domain_data_args.attr.n_unpaired}"
#     - checkpoint_path: "#{default_root_dir}/domain_v.ckpt"
#       domain_type: v_latents

domain_data_args:
    v_latents:
        presaved_path: vae_v_shimmer.npy
    attr:
        n_unpaired: 0
