_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": images/val/ref_v_latents-attr_v_latents.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": images/val/ref_v_latents-attr_v_latents.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/train/ref_v_latents_v_latents.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/train/ref_v_latents_v_latents._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/train/ref_v_latents_v_latents.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/val/ref_v_latents-attr_v_latents.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/val/ref_v_latents-attr_v_latents.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/val/ref_v_latents-attr_v_latents.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/train/ref_v_latents_v_latents.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/train/ref_v_latents_v_latents.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/train/ref_v_latents_v_latents.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": images/val/ref_v_latents-attr_v_latents._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
alpha:
    value: 1
batch_size:
    value: 2056
decoder_layers:
    value: 2
decoder_size:
    value: 256
encoder_layers:
    value: 2
encoder_size:
    value: 256
exclude_colors:
    value: true
fusion_activation_fn:
    value: tanh
latent_dim:
    value: 12
learn_logit_scale:
    value: false
loss_coefs:
    value:
        contrastives: 1
        cycles: 1
        demi_cycles: 1
        translations: 1
lr_base:
    value: 0.00013
max_lr:
    value: 0.00015
max_steps:
    value: 220000
optim_lr:
    value: 1e-05
optim_weight_decay:
    value: 1e-06
scheduler_args:
    value: null
seed:
    value: 1
temperature:
    value: 1
weight_decay:
    value: 1e-06
workspace_dim:
    value: 12
